tap "1password/tap"
tap "hashicorp/tap"
brew "aws-vault"
brew "python@3.11"
brew "awscli", link: false
brew "docker-compose", link: false
brew "e2fsprogs", link: true
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "hping"
brew "lrzsz"
brew "neovim"
brew "nvm"
brew "opentofu"
brew "pnpm"
brew "pyenv"
brew "python@3.10"
brew "starship"
brew "telnet"
brew "terragrunt"
cask "1password-cli"
cask "ollama"
cask "stats"
